import type { MetadataRoute } from 'next';
import { prisma } from '@cc-scale/database';
import { locales, defaultLocale } from '@/i18n/routing';

const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.zzscale.com';

// Sitemap route under [locale] segment. We generate URLs for the CURRENT
// locale only (other locales are generated by their own /[locale]/sitemap.xml).
// Next.js 14 route handlers may not always receive `params` in prod for
// dynamic segments consumed by middleware, so we derive locale from the
// request URL via the standard pattern. If that fails we fall back to the
// default locale so crawlers always get a valid sitemap.
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const lastMod = new Date();
  const now = lastMod.toISOString();

  // Build static entries for every locale so each /[locale]/sitemap.xml
  // is self-contained. This avoids any dependency on params.
  const staticPaths = [
    { path: '', priority: 1.0, freq: 'weekly' as const },
    { path: '/about', priority: 0.8, freq: 'monthly' as const },
    { path: '/products', priority: 0.9, freq: 'weekly' as const },
    { path: '/oem', priority: 0.8, freq: 'monthly' as const },
    { path: '/guarantee', priority: 0.7, freq: 'monthly' as const },
    { path: '/support', priority: 0.6, freq: 'monthly' as const },
    { path: '/certifications', priority: 0.7, freq: 'monthly' as const },
    { path: '/cases', priority: 0.7, freq: 'weekly' as const },
    { path: '/blog', priority: 0.7, freq: 'daily' as const },
    { path: '/contact', priority: 0.9, freq: 'monthly' as const },
    { path: '/ai-summary', priority: 0.4, freq: 'weekly' as const },
  ];

  const staticEntries: MetadataRoute.Sitemap = [];
  for (const loc of locales) {
    const prefix = loc === defaultLocale ? '' : `/${loc}`;
    for (const s of staticPaths) {
      staticEntries.push({
        url: `${baseUrl}${prefix}${s.path}`,
        lastModified: now,
        changeFrequency: s.freq,
        priority: s.priority,
      });
    }
  }

  // Dynamic product pages - one URL per (locale, product)
  let productEntries: MetadataRoute.Sitemap = [];
  try {
    const products = await prisma.product.findMany({
      where: { isActive: true },
      select: { slug: true, updatedAt: true },
      orderBy: { updatedAt: 'desc' },
      take: 1000,
    });
    for (const loc of locales) {
      const prefix = loc === defaultLocale ? '' : `/${loc}`;
      for (const p of products) {
        productEntries.push({
          url: `${baseUrl}${prefix}/products/${p.slug}`,
          lastModified: p.updatedAt.toISOString(),
          changeFrequency: 'weekly',
          priority: 0.7,
        });
      }
    }
  } catch (err) {
    console.warn('sitemap: failed to load products', err);
  }

  // Dynamic blog posts - one URL per (locale, post)
  let blogEntries: MetadataRoute.Sitemap = [];
  try {
    const posts = await prisma.blogPost.findMany({
      where: { isActive: true },
      select: { slug: true, updatedAt: true, publishedAt: true },
      orderBy: { publishedAt: 'desc' },
      take: 200,
    });
    const filtered = posts.filter((p) => p.publishedAt);
    for (const loc of locales) {
      const prefix = loc === defaultLocale ? '' : `/${loc}`;
      for (const p of filtered) {
        blogEntries.push({
          url: `${baseUrl}${prefix}/blog/${p.slug}`,
          lastModified: (p.updatedAt || p.publishedAt).toISOString(),
          changeFrequency: 'monthly',
          priority: 0.6,
        });
      }
    }
  } catch (err) {
    console.warn('sitemap: failed to load blog posts', err);
  }

  return [...staticEntries, ...productEntries, ...blogEntries];
}
